name: Tests (PHP)

on: [push, pull_request]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix:
            php: [7.4]
            os: [ ubuntu-latest ]
            dependency-version: [prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

        services:
          mysql:
            image: mysql:5.7
            env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: scout_testing
            ports:
              - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


        env:
          DB_DATABASE: scout_testing
          DB_USER: root
          DB_PASSWORD: root
          DB_PORT: 3306
          DB_DRIVER: mysql

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring,dom,fileinfo,mysql,imagick,bcmath,pcntl,zip,soap,intl,gd,exif,iconv
                  coverage: none
            - name: Install dependencies
              run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Run tests
              run: ./vendor/bin/codecept run unit
              env:
                  APP_ENV: testing
